version: '3.4'
services:
  certificate_authority:
    build: ./certificate_authority/
    environment:
      - chain_url=http://host.docker.internal:7545
      - host=0.0.0.0
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
      - '8080:8080'
  client01:
    build: ./client/
    environment:
      - chain_url=http://host.docker.internal:7545
      - ca_url=http://host.docker.internal:8080
      - host=0.0.0.0
      - port=8091
      - common_name=client01.com
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
      - '8091:8091'