openapi: '3.0.0'
info:
  title: Privacy aware log based PKI client
  version: '1'
  description: Just trying things out


servers:
- url: http://localhost:8090

paths:
  /new_key:
    post:
      summary: Generates new key and registers it to the CA 
      operationId: app.register
      responses:
        '204':
          description: New certificate successfully registered
  /update_key:
    post:
      summary: Generates new key and registers it to the CA 
      operationId: app.update
      responses:
        '204':
          description: New certificate successfully registered

  /register_status:
    get:
      summary: Gets status of register request sent to the certificate authority
      operationId: app.status
      responses:
        '200':
          description: Transaction status
          content:
            'text/plain':
              schema:
                type: string

  /debug/ca/status:
    post:
      summary: Gets registration request of specific transaction
      operationId: app.ca_status
      requestBody:
        x-body-name: transaction
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: Registration requests from the database
          content:
            'application/json':
              schema:
                type: array
                items:
                  type: object
                  $ref: '#/components/schemas/RegistrationRequest'
        '400':
          description: Bad request
          content:
            'text/plain':
              schema:
                type: string


components:
  schemas:
    Transaction:
      type: object
      properties:
        identity:
          type: string
        public_key:
          type: string
        signatures:
          type: string
    RegistrationRequest:
      type: object
      properties:
        transaction:
          type: object
          $ref: '#/components/schemas/Transaction'
        status:
          type: string
        id:
          type: integer