openapi: '3.0.0'
info:
  title: Privacy aware log based PKI client
  version: '1'
  description: Just trying things out


servers:
- url: http://localhost:8090

paths:
  /ca/register:
    post:
      summary: Applies register transaction for approval
      operationId: app.hello
      responses:
        '200':
          description: Application status
          content:
            'text/plain':
              schema:
                type: string
  /ca/status:
    post:
      summary: Checks transaction status in ca
      operationId: app.hello2
      responses:
        '200':
          description: Application status
          content:
            'text/plain':
              schema:
                type: string
    