openapi: '3.0.0'
info:
  title: Privacy aware log based PKI API
  version: '1'
  description: Just trying things out

paths:
  /register:
    post:
      summary: Applies register transaction for approval
      operationId: app.register_transaction
      requestBody:
        x-body-name: transaction
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: Application status
          content:
            'text/plain':
              schema:
                type: string
        '400':
          description: Bad request
          content:
            'text/plain':
              schema:
                type: string
  
  /get/{id}:
    get:
      summary: Gets a specific transaction from the smart contract
      operationId: app.get_transaction
      parameters:
      - name: id
        in: path
        required: true
        description: the transaction identifier
        schema:
          type: integer
      responses:
        '200':
          description: Fetched transaction from smart contract
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Transaction'
        '404':
          description: Resource not found
          content:
            'text/plain':
              schema:
                type: string
  /admin/requests:
    get:
      summary: Gets all registration requests from the database
      operationId: app.get_all_requests
      responses:
        '200':
          description: Fetched transaction from smart contract
          content:
            'application/json':
              schema:
                type: array
                items:
                  type: object
                  $ref: '#/components/schemas/RegistrationRequest'

components:
  schemas:
    Transaction:
      type: object
      properties:
        identity:
          type: string
        public_key:
          type: string
    RegistrationRequest:
      type: object
      properties:
        transaction:
          type: object
          $ref: '#/components/schemas/Transaction'
        status:
          type: string